version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ttt-backend
    restart: unless-stopped
    environment:
      - PORT=8080
      - HTTPS_PORT=8443
      - CORS_ORIGIN=${CORS_ORIGIN:-https://ticktocktasks.com}
      - JWT_SECRET=${JWT_SECRET:-change-this-in-production}
      - NODE_ENV=production
      - WEB_PUSH_PUBLIC_KEY=${WEB_PUSH_PUBLIC_KEY}
      - WEB_PUSH_PRIVATE_KEY=${WEB_PUSH_PRIVATE_KEY}
      - CERT_HOSTS=${CERT_HOSTS:-localhost}
      - REDIRECT_HTTP_TO_HTTPS=false
    ports:
      - "8080:8080"
      - "8443:8443"
    labels:
      - "autoheal=true"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/healthz || curl -skf https://localhost:8443/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  nginx:
    image: nginx:alpine
    container_name: ttt-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - letsencrypt:/etc/letsencrypt
      - certbot_challenges:/var/www/certbot
    depends_on:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- --no-check-certificate https://127.0.0.1/healthz >/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  letsencrypt:
  certbot_challenges:
