version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: ticktock-backend
    restart: unless-stopped
    environment:
      - PORT=8080
      - HTTPS_PORT=8443
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:8000}
      - JWT_SECRET=${JWT_SECRET:-change-this-in-production}
      - NODE_ENV=production
      - SQLITE_FILE=/data/data.sqlite
      - WEB_PUSH_PUBLIC_KEY=${WEB_PUSH_PUBLIC_KEY}
      - WEB_PUSH_PRIVATE_KEY=${WEB_PUSH_PRIVATE_KEY}
      - CERT_HOSTS=${CERT_HOSTS:-localhost,192.168.1.6}
      - REDIRECT_HTTP_TO_HTTPS=${REDIRECT_HTTP_TO_HTTPS:-true}
    volumes:
      - backend_data:/data
    ports:
      - "8080:8080"    # optional HTTP -> HTTPS redirect or API if disabled
      - "8443:8443"    # HTTPS
    labels:
      - "autoheal=true"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  caddy:
    image: caddy:2
    container_name: ticktock-caddy
    restart: unless-stopped
    profiles: ["proxy"]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - backend
volumes:
  backend_data:
