name: DEPRECATED - Frontend deploy (CloudFront/S3 removed)

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Frontend deploy is disabled
        run: |
          echo "This repository no longer deploys the frontend to S3/CloudFront." >> $GITHUB_STEP_SUMMARY
          echo "The frontend is served by Nginx on the same EC2 instance as the backend." >> $GITHUB_STEP_SUMMARY
          echo "To deploy, SSH/SSM to the EC2 host, pull latest code, and run: docker compose up -d --build" >> $GITHUB_STEP_SUMMARY
          echo "Exiting without action."